Repository railroadmedia/musora-content-services, pull requests merged in 2025-06, with the labels that each got.

#301 chore(v1): enable conventional commits PR validation
  .github/workflows/conventional-commits.yaml
Labels: chore

#304 feat(MU2-712): Add live_event_start_time and live_event_end_time on fetchUpcomingEvents
  src/services/sanity.js
Labels: feature

#308 fix(MU2-608): Sort recent lessons by user progress
  src/services/content.js
  src/services/contentProgress.js
  src/services/sanity.js
Labels: fix

#314 feat: fetch lesson content logo
  src/contentTypeConfig.js
  src/services/sanity.js
Labels: feature

#311 feat(BEH-541): guided course enrollment page endpoint
  src/index.d.ts
  src/index.js
  src/services/content-org/guided-courses.ts
  src/services/contentProgress.js
Labels: feature

#312 refactor: addevent field name
  src/services/sanity.js
Labels: refactor
