Repository railroadmedia/musora-content-services, pull requests merged in 2025-10, with the labels that each got.

#469 feat(MU2-1111): New method for forum rules
  docs/ContentOrganization.html
  docs/Forums.html
  docs/Gamification.html
  docs/UserManagementSystem.html
  docs/api_types.js.html
  docs/config.js.html
  docs/content-org_content-org.js.html
  docs/content-org_guided-courses.ts.html
  docs/content-org_playlists-types.js.html
  docs/content-org_playlists.js.html
  docs/content.js.html
  docs/forums_categories.ts.html
  docs/forums_forums.ts.html
  docs/forums_posts.ts.html
  docs/forums_threads.ts.html
  docs/gamification_awards.ts.html
  docs/gamification_gamification.js.html
  docs/global.html
  docs/index.html
  docs/module-Accounts.html
  docs/module-Awards.html
  docs/module-Config.html
  docs/module-Content-Services-V2.html
  docs/module-Forums.html
  docs/module-GuidedCourses.html
  docs/module-Interests.html
  docs/module-Payments.html
  docs/module-Permissions.html
  docs/module-Playlists.html
  docs/module-Railcontent-Services.html
  docs/module-Sanity-Services.html
  docs/module-Sessions.html
  docs/module-UserActivity.html
  docs/module-UserChat.html
  docs/module-UserManagement.html
  docs/module-UserMemberships.html
  docs/module-UserNotifications.html
  docs/module-UserProfile.html
  docs/railcontent.js.html
  docs/sanity.js.html
  docs/userActivity.js.html
  docs/user_account.ts.html
  docs/user_chat.js.html
  docs/user_interests.js.html
  docs/user_management.js.html
  docs/user_memberships.js.html
  docs/user_notifications.js.html
  docs/user_payments.ts.html
  docs/user_permissions.js.html
  docs/user_profile.js.html
  docs/user_sessions.js.html
  docs/user_types.js.html
  docs/user_user-management-system.js.html
  src/index.d.ts
  src/index.js
  src/services/forums/posts.ts
Labels: feature

#459 refactor(TP-1002): remove Drumeo shows
  src/contentTypeConfig.js
Labels: refactor

#475 fix(MU2-1124): Reverts MU2-922
  src/contentTypeConfig.js
  src/index.d.ts
  src/index.js
  src/services/content.js
  src/services/railcontent.js
  src/services/sanity.js
  test/contentProgress.test.js
Labels: fix

#478 feat(MU2E2-57): New search method for forum
  docs/ContentOrganization.html
  docs/Forums.html
  docs/Gamification.html
  docs/UserManagementSystem.html
  docs/api_types.js.html
  docs/config.js.html
  docs/content-org_content-org.js.html
  docs/content-org_guided-courses.ts.html
  docs/content-org_playlists-types.js.html
  docs/content-org_playlists.js.html
  docs/content.js.html
  docs/forums_categories.ts.html
  docs/forums_forums.ts.html
  docs/forums_posts.ts.html
  docs/forums_threads.ts.html
  docs/gamification_awards.ts.html
  docs/gamification_gamification.js.html
  docs/global.html
  docs/index.html
  docs/module-Accounts.html
  docs/module-Awards.html
  docs/module-Config.html
  docs/module-Content-Services-V2.html
  docs/module-Forums.html
  docs/module-GuidedCourses.html
  docs/module-Interests.html
  docs/module-Payments.html
  docs/module-Permissions.html
  docs/module-Playlists.html
  docs/module-Railcontent-Services.html
  docs/module-Sanity-Services.html
  docs/module-Sessions.html
  docs/module-UserActivity.html
  docs/module-UserChat.html
  docs/module-UserManagement.html
  docs/module-UserMemberships.html
  docs/module-UserNotifications.html
  docs/module-UserProfile.html
  docs/railcontent.js.html
  docs/sanity.js.html
  docs/userActivity.js.html
  docs/user_account.ts.html
  docs/user_chat.js.html
  docs/user_interests.js.html
  docs/user_management.js.html
  docs/user_memberships.js.html
  docs/user_notifications.js.html
  docs/user_payments.ts.html
  docs/user_permissions.js.html
  docs/user_profile.js.html
  docs/user_sessions.js.html
  docs/user_types.js.html
  docs/user_user-management-system.js.html
  src/index.d.ts
  src/index.js
  src/services/forums/posts.ts
Labels: feature
