Repository railroadmedia/musora-content-services, pull requests merged in 2025-08, with the labels that each got.

#392 fix(T3PS-120): allow falsey values for description and category
  src/services/content-org/playlists-types.js
  src/services/content-org/playlists.js
Labels: fix

#386 fix(T3PS-602): fixes thumbnail data missing from getNewAndUpcoming MCS method
  src/services/sanity.js
Labels: fix

#394 chore(MU2-897): hard code award data for alpha
  src/services/gamification/awards.js
  src/services/gamification/types.js
Labels: chore

#389 feat(navigateTo): Add navigateTo context and update homepageprogress rows to pull the same data as other locations
  src/contentTypeConfig.js
  src/services/content-org/playlists.js
  src/services/content.js
  src/services/contentAggregator.js
  src/services/contentProgress.js
  src/services/recommendations.js
  src/services/sanity.js
  src/services/userActivity.js
Labels: feature

#391 fix(MU2-907): scheduled content appearing in new releases
  link_mcs.sh
  src/services/sanity.js
Labels: fix

#384 fix(BEH-845): enable soft deletes for user activities
  src/index.d.ts
  src/index.js
  src/services/user/notifications.js
  src/services/userActivity.js
Labels: fix

#397 fix: null check on buildNavigateTo
  src/services/contentProgress.js
Labels: fix

#398 fix: MU2-916 -Add navigateTo and parentId to practice tracker and recent activity
  src/services/userActivity.js
Labels: fix

#396 fix: MU2-912 - fix pagination for Incomplete and Completed tabs
  src/services/sanity.js
Labels: fix

#406 feat(BEH-601): fix parent list coming as null due to erroneous query
  src/filterBuilder.js
  src/services/sanity.js
Labels: feature

#410 fix(MU-921): add context to content empty arrays
  src/services/contentAggregator.js
  src/services/userActivity.js
Labels: fix

#415 fix: brand query param optional
  src/services/sanity.js
Labels: fix

#411 fix(MU-922): uses BE for fetching recent content items
  src/contentTypeConfig.js
  src/index.d.ts
  src/index.js
  src/services/content.js
  src/services/railcontent.js
  src/services/sanity.js
  test/contentProgress.test.js
Labels: fix

#422 feat(MU2-956): display name update
  docs/ContentOrganization.html
  docs/Gamification.html
  docs/UserManagementSystem.html
  docs/api_types.js.html
  docs/config.js.html
  docs/content-org_content-org.js.html
  docs/content-org_playlists-types.js.html
  docs/content-org_playlists.js.html
  docs/content.js.html
  docs/gamification_awards.js.html
  docs/gamification_gamification.js.html
  docs/gamification_types.js.html
  docs/global.html
  docs/index.html
  docs/module-Awards.html
  docs/module-Config.html
  docs/module-Content-Services-V2.html
  docs/module-Interests.html
  docs/module-Permissions.html
  docs/module-Playlists.html
  docs/module-Railcontent-Services.html
  docs/module-Sanity-Services.html
  docs/module-Sessions.html
  docs/module-UserActivity.html
  docs/module-UserChat.html
  docs/module-UserManagement.html
  docs/module-UserNotifications.html
  docs/module-UserProfile.html
  docs/railcontent.js.html
  docs/sanity.js.html
  docs/userActivity.js.html
  docs/user_chat.js.html
  docs/user_interests.js.html
  docs/user_management.js.html
  docs/user_notifications.js.html
  docs/user_permissions.js.html
  docs/user_profile.js.html
  docs/user_sessions.js.html
  docs/user_types.js.html
  docs/user_user-management-system.js.html
  src/index.d.ts
  src/index.js
  src/services/user/management.js
Labels: feature

#423 fix: progress rows throws error for empty progress
  src/services/userActivity.js
Labels: fix

#427 chore(coderabbitai): filter review path
  .coderabbit.yaml
Labels: chore

#428 docs: update docs with ts files
  docs/ContentOrganization.html
  docs/Gamification.html
  docs/UserManagementSystem.html
  docs/api_types.js.html
  docs/config.js.html
  docs/content-org_content-org.js.html
  docs/content-org_guided-courses.ts.html
  docs/content-org_playlists-types.js.html
  docs/content-org_playlists.js.html
  docs/content.js.html
  docs/gamification_awards.ts.html
  docs/gamification_gamification.js.html
  docs/global.html
  docs/index.html
  docs/module-Accounts.html
  docs/module-Awards.html
  docs/module-Config.html
  docs/module-Content-Services-V2.html
  docs/module-GuidedCourses.html
  docs/module-Interests.html
  docs/module-Permissions.html
  docs/module-Playlists.html
  docs/module-Railcontent-Services.html
  docs/module-Sanity-Services.html
  docs/module-Sessions.html
  docs/module-UserActivity.html
  docs/module-UserChat.html
  docs/module-UserManagement.html
  docs/module-UserNotifications.html
  docs/module-UserProfile.html
  docs/railcontent.js.html
  docs/sanity.js.html
  docs/userActivity.js.html
  docs/user_account.ts.html
  docs/user_chat.js.html
  docs/user_interests.js.html
  docs/user_management.js.html
  docs/user_notifications.js.html
  docs/user_permissions.js.html
  docs/user_profile.js.html
  docs/user_sessions.js.html
  docs/user_types.js.html
  docs/user_user-management-system.js.html
  src/services/user/account.ts
Labels: documentation
