Repository railroadmedia/musora-content-services, pull requests merged in 2025-07, with the labels that each got.

#315 fix: (BR-286) fetchLessonContent for users without access
  src/services/sanity.js
Labels: fix

#324 feat: MU2-759 New method to fetch a single comment by its ID
  docs/ContentOrganization.html
  docs/Gamification.html
  docs/UserManagementSystem.html
  docs/api_types.js.html
  docs/config.js.html
  docs/content-org_content-org.js.html
  docs/content-org_playlists-types.js.html
  docs/content-org_playlists.js.html
  docs/content.js.html
  docs/gamification_awards.js.html
  docs/gamification_gamification.js.html
  docs/gamification_types.js.html
  docs/global.html
  docs/index.html
  docs/module-Awards.html
  docs/module-Config.html
  docs/module-Content-Services-V2.html
  docs/module-Interests.html
  docs/module-Permissions.html
  docs/module-Playlists.html
  docs/module-Railcontent-Services.html
  docs/module-Sanity-Services.html
  docs/module-Sessions.html
  docs/module-UserActivity.html
  docs/module-UserChat.html
  docs/module-UserManagement.html
  docs/module-UserNotifications.html
  docs/module-UserProfile.html
  docs/railcontent.js.html
  docs/sanity.js.html
  docs/userActivity.js.html
  docs/user_chat.js.html
  docs/user_interests.js.html
  docs/user_management.js.html
  docs/user_notifications.js.html
  docs/user_permissions.js.html
  docs/user_profile.js.html
  docs/user_sessions.js.html
  docs/user_types.js.html
  docs/user_user-management-system.js.html
  src/index.d.ts
  src/index.js
  src/services/railcontent.js
Labels: feature

#328 feat: MU2-761: Sort by 'recommended'
  src/services/sanity.js
Labels: feature

#323 feat: MU2-583: Update notification settings routes
  src/services/user/notifications.js
Labels: feature

#326 feat(BEH-706): add continue behaviour to lessons collection page and index page
  src/contentTypeConfig.js
  src/index.d.ts
  src/index.js
  src/services/contentAggregator.js
  src/services/contentProgress.js
  src/services/userActivity.js
Labels: feature

#335 chore(beh-706): lessons collection page
  src/services/contentAggregator.js
  src/services/contentProgress.js
  src/services/sanity.js
Labels: chore

#332 feat(BEH-662): add pinned guided course to homepage
  src/contentTypeConfig.js
  src/services/content-org/guided-courses.ts
  src/services/sanity.js
  src/services/userActivity.js
Labels: feature

#337 feat(BEH-572): ai recommender row categories
  src/contentTypeConfig.js
  src/index.d.ts
  src/index.js
  src/services/content.js
  src/services/contentAggregator.js
  src/services/recommendations.js
  src/services/sanity.js
Labels: feature

#342 fix(merge-conflict): Patch for for you page + collection modules
  src/services/contentAggregator.js
  src/services/contentProgress.js
Labels: fix

#341 fix: MU2-787 Leaving Soon and Returning should only be set in the future
  src/contentTypeConfig.js
  src/services/sanity.js
Labels: fix

#336 fix(BEH-705): handle pack index page data
  src/contentTypeConfig.js
Labels: fix

#348 chore: system alpha user state
  src/services/forum.js
  src/services/gamification/awards.js
Labels: chore

#346 feat(BEH-837): update contentAggregator to process parent + children
  src/contentTypeConfig.js
  src/services/content.js
  src/services/contentAggregator.js
  src/services/contentProgress.js
  src/services/sanity.js
  src/services/userActivity.js
Labels: feature

#350 fix: MU2-645 Add Sanity type and content slug to auto user practices
  src/services/userActivity.js
Labels: fix

#343 feat(MU2-825): user data function
  docs/ContentOrganization.html
  docs/Gamification.html
  docs/UserManagementSystem.html
  docs/api_types.js.html
  docs/config.js.html
  docs/content-org_content-org.js.html
  docs/content-org_playlists-types.js.html
  docs/content-org_playlists.js.html
  docs/content.js.html
  docs/gamification_awards.js.html
  docs/gamification_gamification.js.html
  docs/gamification_types.js.html
  docs/global.html
  docs/index.html
  docs/module-Awards.html
  docs/module-Config.html
  docs/module-Content-Services-V2.html
  docs/module-Interests.html
  docs/module-Permissions.html
  docs/module-Playlists.html
  docs/module-Railcontent-Services.html
  docs/module-Sanity-Services.html
  docs/module-Sessions.html
  docs/module-UserActivity.html
  docs/module-UserChat.html
  docs/module-UserManagement.html
  docs/module-UserNotifications.html
  docs/module-UserProfile.html
  docs/railcontent.js.html
  docs/sanity.js.html
  docs/userActivity.js.html
  docs/user_chat.js.html
  docs/user_interests.js.html
  docs/user_management.js.html
  docs/user_notifications.js.html
  docs/user_permissions.js.html
  docs/user_profile.js.html
  docs/user_sessions.js.html
  docs/user_types.js.html
  docs/user_user-management-system.js.html
  src/index.d.ts
  src/index.js
  src/services/user/management.js
Labels: feature

#354 chore(catalog): Add enrollment start/end fields
  src/contentTypeConfig.js
  src/services/sanity.js
Labels: chore

#353 fix: recent lessons do not displayed children lessons
  src/contentTypeConfig.js
Labels: fix

#344 feat(BEH-38): add context data to tab results
  src/services/content.js
  src/services/contentProgress.js
  src/services/sanity.js
Labels: feature

#356 fix: user data endpoint
  src/services/user/management.js
Labels: fix

#351 feat: MU2-805 Set a pauseLiveEventPollingUntil field when user mark all notificatio…
  src/services/user/notifications.js
Labels: feature

#340 fix: collection module endpoint changes
  src/index.d.ts
  src/index.js
  src/services/sanity.js
Labels: fix

#359 fix: T3PS-21: Live Stream content cards in the Progress Row and Recent Lessons
  src/services/sanity.js
  src/services/userActivity.js
Labels: fix

#364 fix: T3PS-266 - Practice tracker meta
  src/contentTypeConfig.js
  src/services/contentProgress.js
Labels: fix

#368 fix: Migrate to dayjs
  package-lock.json
  package.json
  src/index.d.ts
  src/index.js
  src/services/dateUtils.js
  src/services/railcontent.js
  src/services/userActivity.js
Labels: fix

#374 fix(T3PS-426): Delete last practice from a session
  src/services/userActivity.js
Labels: fix

#372 fix: T3PS-272 Update course part meta
  src/contentTypeConfig.js
Labels: fix

#376 fix: T3PS-501: Homepage progress rows - content types
  src/services/userActivity.js
Labels: fix

#366 feat: added parent id for multi-level content
  src/contentTypeConfig.js
  src/services/sanity.js
Labels: feature

#377 fix(BEH-873): Lessons Featuring this Song and Other Versions of this Song, restricted to current brand
  src/services/sanity.js
  yarn.lock
Labels: fix

#379 fix(verbs): fix open/closeComment. depreciate patchDataHandler
  docs/ContentOrganization.html
  docs/Gamification.html
  docs/UserManagementSystem.html
  docs/api_types.js.html
  docs/config.js.html
  docs/content-org_content-org.js.html
  docs/content-org_playlists-types.js.html
  docs/content-org_playlists.js.html
  docs/content.js.html
  docs/gamification_awards.js.html
  docs/gamification_gamification.js.html
  docs/gamification_types.js.html
  docs/global.html
  docs/index.html
  docs/module-Awards.html
  docs/module-Config.html
  docs/module-Content-Services-V2.html
  docs/module-Interests.html
  docs/module-Permissions.html
  docs/module-Playlists.html
  docs/module-Railcontent-Services.html
  docs/module-Sanity-Services.html
  docs/module-Sessions.html
  docs/module-UserActivity.html
  docs/module-UserChat.html
  docs/module-UserManagement.html
  docs/module-UserNotifications.html
  docs/module-UserProfile.html
  docs/railcontent.js.html
  docs/sanity.js.html
  docs/userActivity.js.html
  docs/user_chat.js.html
  docs/user_interests.js.html
  docs/user_management.js.html
  docs/user_notifications.js.html
  docs/user_permissions.js.html
  docs/user_profile.js.html
  docs/user_sessions.js.html
  docs/user_types.js.html
  docs/user_user-management-system.js.html
  src/services/railcontent.js
Labels: fix

#365 chore(BEH-614): delete challenge endpoints
  docs/Content-Organization.html
  docs/ContentOrganization.html
  docs/Gamification.html
  docs/UserManagement.html
  docs/UserManagementSystem.html
  docs/api_types.js.html
  docs/config.js.html
  docs/content-org_content-org.js.html
  docs/content-org_playlists-types.js.html
  docs/content-org_playlists.js.html
  docs/content.js.html
  docs/gamification_awards.js.html
  docs/gamification_gamification.js.html
  docs/gamification_types.js.html
  docs/global.html
  docs/global.html#User
  docs/index.html
  docs/module-Awards.html
  docs/module-Config.html
  docs/module-Content-Services-V2.html
  docs/module-Interests.html
  docs/module-Notifications.html
  docs/module-Permissions.html
  docs/module-Playlists.html
  docs/module-Railcontent-Services.html
  docs/module-Sanity-Services.html
  docs/module-Session-Management.html
  docs/module-Sessions.html
  docs/module-User-Activity.html
  docs/module-User-Management.html
  docs/module-User-Permissions.html
  docs/module-UserActivity.html
  docs/module-UserChat.html
  docs/module-UserManagement.html
  docs/module-UserNotifications.html
  docs/module-UserProfile.html
  docs/railcontent.js.html
  docs/sanity.js.html
  docs/types.js.html
  docs/userActivity.js.html
  docs/user_chat.js.html
  docs/user_interests.js.html
  docs/user_management.js.html
  docs/user_notifications.js.html
  docs/user_permissions.js.html
  docs/user_profile.js.html
  docs/user_sessions.js.html
  docs/user_types.js.html
  docs/user_user-management-system.js.html
  docs/user_user-management.js.html
  src/contentMetaData.js
  src/contentTypeConfig.js
  src/index.d.ts
  src/index.js
  src/services/content.js
  src/services/railcontent.js
  src/services/sanity.js
  src/services/userActivity.js
  test/live/railcontentLive.test.js
  test/sanityQueryService.test.js
Labels: chore

#382 fix(nullcheck): patch for null sanity results and null check in relatedByLicense
  src/services/sanity.js
Labels: fix

#380 fix(T3PS-454): rank lessons by recommended
  src/services/content.js
  src/services/sanity.js
Labels: fix

#383 fix(T3PS-139): fix lesson count on content cards
  src/services/sanity.js
Labels: fix

#387 fix(T3PS-594): wrong active date mobile
  src/services/userActivity.js
Labels: fix
